name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH and Docker login
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          docker login -u shaharrel1 -p ${{ secrets.WORKFLOW_TOKEN }}

      - name: Build Docker image
        run: docker build -t shaharrel1/my-node-project:latest .

      - name: Push Docker image
        run: docker push shaharrel1/my-node-project:latest
