name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(cat VERSION || echo "0")
          echo "VERSION=$((VERSION + 1))" > VERSION
          echo "::set-output name=version::$VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.WORKFLOW_USERNAME }}
          password: ${{ secrets.WORKFLOW_SECRET }}

      - name: Build Docker image
        run: docker build -t shaharrel/my-node-project:v${{ steps.get_version.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push shaharrel/my-node-project:v${{ steps.get_version.outputs.version }}
