name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current commit hash
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Get current datetime
        id: get_datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

      - name: Set image tag
        id: set_image_tag
        run: |
          echo "VERSION=${{ steps.get_commit_hash.outputs.commit_hash }}-${{ steps.get_datetime.outputs.datetime }}" > VERSION
          echo "::set-output name=version::${{ steps.get_commit_hash.outputs.commit_hash }}-${{ steps.get_datetime.outputs.datetime }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.WORKFLOW_USERNAME }}
          password: ${{ secrets.WORKFLOW_SECRET }}

      - name: Build Docker image
        run: docker build -t shaharrel/my-node-project:${{ steps.set_image_tag.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push shaharrel/my-node-project:${{ steps.set_image_tag.outputs.version }}
